### ISSUE TITLE
`Type: Epic` automation setup request

### ISSUE THREAD

**Issue by brentc** [getsentry/team-ospo#100]
### From

Team: Mobile Developer Experience

### To

MDX

**Comment by brentc** [comment]
We've mostly moved over to GitHub for project planning. This is so we can sync our GH project plan tasks with Jira for Eng reporting.

**Comment by chadwhitacre** [comment]
Our first in `sentry`, let's do it! Here's [a PR to add the label](https://github.com/getsentry/sentry/pull/44028), I'm seeing a perms issue in Unito so I'll need to resolve that as well.

<img width="388" alt="missing perms" src="https://user-images.githubusercontent.com/134455/216383740-af49a26c-2272-4559-8299-5b227bd8b1c7.png">

**Comment by chadwhitacre** [comment]
PR landed, need to resolve perms issue.

**Comment by chadwhitacre** [comment]
I pinged IT about it.

**Comment by chadwhitacre** [comment]
I [filed a ticket](https://getsentry.atlassian.net/servicedesk/customer/portal/4/ISD-4205).

**Comment by chadwhitacre** [comment]
Resolved! The MDE project in Jira had had "Adminstrators" removed from it, only Global Admins could modify.

**Comment by chadwhitacre** [comment]
Okay @brentc this is ready. Can you test it out by labeling an issue in the `sentry` repo with both `Type: Epic` and `Team: Mobile Developer Experience`? The expected result is a synced epic issue created in the MDE Jira board that also shows up on [Releases](https://getsentry.atlassian.net/plugins/servlet/ac/com.almworks.jira.structure/structure-widget#!s:97).

**Comment by brentc** [comment]
> Resolved! The MDE project in Jira had had "Adminstrators" removed from it, only Global Admins could modify.

Ah, my bad. I only created the project this week, and guess I didn't get the permissions right.

**Comment by brentc** [comment]
I added the `Type: Epic` label to getsentry/sentry#43833.

Not seeing anything happen yet....

**Comment by brentc** [comment]
Also some how getsentry/sentry#43973 and getsentry/sentry#42044 got added to the [Jira MDX project](https://getsentry.atlassian.net/browse/MDX)

**Comment by chadwhitacre** [comment]
Sigh. Sorry for the mix-up. Turns out it's seemingly not possible to match on the presence of two labels, I didn't notice until now that the condition for the team label is "is not." 🙄

<img width="590" alt="is not" src="https://user-images.githubusercontent.com/134455/216693207-d5474987-076d-4203-bd21-f0fde998e9b5.png">

I'll work with Zac to move those errant epics to the right project.

**Comment by chadwhitacre** [comment]
Okay phew it's a multiselect. :]

<img width="617" alt="phew" src="https://user-images.githubusercontent.com/134455/216694022-04184555-95a6-48ad-b18e-c845206331ab.png">

Seeing https://github.com/getsentry/sentry/issues/43833 synced! We good?

**Comment by brentc** [comment]
Looks like it! 🎉

**Comment by brentc** [comment]
Had to reopen because I didn't setup the original project properly (that's why the permissions were weird when you looked into it).

The new MDX project is this one: https://getsentry.atlassian.net/jira/software/c/projects/MDXN

**Comment by brentc** [comment]
@chadwhitacre while you weren't looking, I broke the syncing badly.

Every newly sync'd MDX Epic goes to the FEEDBACK board (as a task) 😢

**Comment by chadwhitacre** [comment]
Hey right so this is a mess, it turns out that these are OR'd not AND'd. 😭 😩 😖

<img width="520" alt="OR" src="https://user-images.githubusercontent.com/134455/218535820-83e78027-7139-4809-ba79-480ece301f8e.png">

This means that all of the flows I thought were separate are in fact in a race condition to "capture" GitHub issues as they're created with the `Type: Epic` label, regardless of the project.

<img width="1152" alt="disabled" src="https://user-images.githubusercontent.com/134455/218536084-9f25d806-6e4b-42a2-b027-5230174ce4cb.png">

At this point I'm bailing on the automation, I had hoped to put something together quickly that helps us out but it's been two weeks and despite working with Unito support this is not converging on a workable solution. Sorry, gonna have to drop back to manual creation/linking. I've disabled all of the automations, I'll update docs soon and also try to clean everything up here asap. :(

**Comment by chadwhitacre** [comment]
Closing this and will track overall switch to manual in https://github.com/getsentry/team-ospo/issues/106.

Sorry @brentc. 😞

**Comment by brentc** [comment]
Ah, too bad. If you need any help with future attempts to get things working, let me know! Happy to try all sorts of things to get something working here.
